### ISSUE TITLE
Unable to delete a local repository programatically

### ISSUE THREAD

**Issue by MarzukhAsjad** [MarzukhAsjad/package-mapper#1]
### Issue Description:

Currently the deleteRepository() in `src\main\java\com\example\mizookie\packagemapper\services\github\GithubRepositoryService.java` is unable to remove the `.git` folder when trying to delete the downloaded repository. The only possible scenario when the `.git` folder **is** removed is when I restart the application and then try deleteing it. Only **then** is the `.git` folder removed. 

### There may be some theories as to why this happens:

1. The .git folder is read only but I have attempted to make this write + executable but still failed to delete it.
2. I am building this on VSCode and VSCode holds the .git somehow for version control. I have tried to move this path outside the project scope but it still is not deleted.

### Possible directives to solve this issue:

1. Figure out how to remove the `.git` folder programmatically.
2. Figure out how to seamlessly restart the application when the `/repository/delete` endpoint is hit before calling the `deleteRepository()`

**Comment by abinjoseplappallil** [comment]
checked the issue and this code is working 
checked the possible reason for this issue . git file is opened by some program causing unable to delete
